# modify to correct paths of your option
# The paths assume that you are running from
# /contents/yolov5
train: ../DLTrafficCounter/data/bbox_highway_split/train
val: ../DLTrafficCounter/data/bbox_highway_split/val
test: ../DLTrafficCounter/data/bbox_highway_split/test

# number of classes
nc: 3

# class names
names: ['car', 'bus', 'truck']